version: '3'

services:
  postgres:
    container_name: PostgreSQL
    image: postgres:14
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=sinbot_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 8000:5432

  express_server:
    container_name: ExpressServer
    volumes:
      - ./backend:/src/
      - expressmodules:/src/node_modules
    build: "./backend"
    command: npm run dev --verbose
    ports:
      - "8002:3000"
    depends_on:
      - postgres

  discord_bot:
    container_name: DiscordBot
    volumes:
      - ./discord_sin_bot:/src/
      - botmodules:/src/node_modules
    build: "./discord_sin_bot"
    command: npm run dev --verbose
    ports:
      - "8001:8080"
    depends_on:
      - express_server

volumes:
  expressmodules: {}
  botmodules: {}